#!/usr/bin/env python

import sys
import pyperclip

if __name__ == "__main__":
flag = 0

if len(sys.argv) < 2:
  print("Usage: markur url [Tag]")
  sys.exit()

url = sys.argv[1]

if len(sys.argv) > 2:
  tag = sys.argv[2]
else:
  tag = url 

protocols = [
  'http', 'https', 
  'ftp', 'git'
]

for protocol in protocols:
  if protocol in url:
    flag = 1
    break

if flag:
  markdowned = "[%s](%s)" % (tag, url)

else:
  url = "http://" + url
  markdowned = "[%s](%s)" % (tag, url)

print(markdowned)
pyperclip.copy(markdowned)
